version: "3"
services:

  web:
    build: .
    #ports:
    #  - "8000:8000"
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./Emergenze-Verbatel:/home/py4web/apps/emergenze
