name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - boltons=23.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - conda=23.7.4
  - conda-package-handling=1.9.0
  - cryptography=38.0.1
  - idna=3.4
  - jsonpatch=1.33
  - jsonpointer=2.4
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.38
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libnsl=2.0.0
  - libpq=16.0
  - libsqlite=3.43.2
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - llvm-openmp=17.0.2
  - ncurses=6.4
  - openssl=3.1.3
  - packaging=23.2
  - pip=23.2.1
  - pluggy=1.0.0
  - psycopg=3.1.12
  - psycopg-c=3.1.12
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.18
  - python_abi=3.9
  - readline=8.2
  - requests=2.28.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - setuptools=65.5.0
  - sqlite=3.40.0
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.64.1
  - tzdata=2022g
  - urllib3=1.26.13
  - wheel=0.41.2
  - xz=5.2.8
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiofiles==23.1.0
      - aiogram==3.1.1
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - frozenlist==1.4.0
      - magic-filter==1.0.12
      - multidict==6.0.4
      - psycopg-binary==3.2.1
      - pydantic==2.3.0
      - pydantic-core==2.6.3
      - typing-extensions==4.7.1
      - yarl==1.9.2

