version: '3.8'

services:

  botgram:
    container_name: emergenze-bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UNAME=${ENVUSER}
        - BOT_TOKEN=${BOT_TOKEN}
        - UID=${UID}
        - GID=${GID}
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      EMERGENZE_BOT_TOKEN: ${EMERGENZE_BOT_TOKEN}
      EMERGENZE_COC_BOT_TOKEN: ${EMERGENZE_COC_BOT_TOKEN}
    # restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./emergenze:/home/${ENVUSER}/emergenze:w
