version: '3.8'

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.27.0.0/24"
        # - subnet: "192.168.189.0/24"

services:

  botgram_emergenze:
    container_name: emergenze-bot
    build:
      context: .
      dockerfile: ./docker/emergenze/Dockerfile
      args:
        - UNAME=${ENVUSER}
        - UID=${UID}
        - GID=${GID}
    environment:
      EMERGENZE_BOT_TOKEN: ${EMERGENZE_BOT_TOKEN}
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./bots:/home/${ENVUSER}/bots:w
      - /home/local/COMGE/egter01/emergenze_uploads/telegram:/home/${ENVUSER}/emergenze_uploads/telegram:w

  botgram_convocazione_coc:
    container_name: convocazione_coc-bot
    build:
      context: .
      dockerfile: ./docker/convocazione_coc/Dockerfile
      args:
        - UNAME=${ENVUSER}
        - UID=${UID}
        - GID=${GID}
    environment:
      ENVUSER: ${ENVUSER}
      EMERGENZE_COC_BOT_TOKEN: ${EMERGENZE_COC_BOT_TOKEN}
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./bots:/home/${ENVUSER}/bots:w
      - ./logs:/home/${ENVUSER}/log
